version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: node-api-vanilla:latest
    container_name: node-api-vanilla-container
    ports:
      - "8000:8000"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      NODE_ENV: development
    command: npm start

networks:
  default:
    driver: bridge